const pair = (fr, en) => ({ fr, en });

export const projects = [
  { id: 'velora', name: 'Maison Velora', categories: ['social', 'branding'], image: 'velora.webp', ratio: '4/3', label: pair('Identité & contenu social', 'Brand direction & social content'), description: pair('Une étude de direction visuelle pour un hôtel boutique fictif. Une palette chaleureuse, une identité éditoriale et un univers cohérent pour les publications et stories.', 'A visual direction study for a fictional boutique hotel. A warm palette, an editorial identity and a consistent world for posts and stories.'), url: 'https://dribbble.com/shots/27545652-Maison-Velora-Luxury-Hotel-Social-Media-Kit' },
  { id: 'aurea', name: 'AUREA', categories: ['web'], image: 'aurea.webp', ratio: '952/761', label: pair('Web design & dashboard', 'Web design & dashboard'), description: pair('Un concept indépendant de plateforme marketing. Un site premium et un dashboard structurés autour de la lisibilité, des fonctionnalités et du parcours utilisateur.', 'An independent marketing platform concept. A premium website and dashboard organised around readability, functionality and the user journey.'), url: 'https://dribbble.com/shots/27552856-AUREA-Luxury-AI-Marketing-Platform' },
  { id: 'jacqueline', name: 'Jacqueline Créatif', categories: ['branding'], image: 'jacqueline.webp', ratio: '4/3', label: pair('Logo & système de marque', 'Logo & brand system'), description: pair('Un concept de marque créative autour d’un monogramme géométrique. Noir, blanc et rouge donnent du rythme aux déclinaisons de l’identité.', 'A creative brand concept built around a geometric monogram. Black, white and red bring energy to the identity and its applications.'), url: 'https://dribbble.com/shots/27549241-Jacqueline-Cr-atif-Modern-Creative-Logo-System' },
  { id: 'fitslim', name: 'FitSlim Coach', categories: ['web'], image: 'fitslim.webp', ratio: '1200/657', label: pair('Interface d’application mobile', 'Mobile app interface'), description: pair('Une étude d’interface mobile pour une application de fitness fictive : séances, progression et habitudes quotidiennes dans une expérience visuelle claire.', 'A mobile interface study for a fictional fitness app: workouts, progress and daily habits in a clear visual experience.'), url: 'https://dribbble.com/shots/27560510-FitSlim-Coach-Personalized-Fitness-Weight-Loss-App' },
  { id: 'lumina', name: 'Lumina AI', categories: ['web'], image: 'lumina.webp', ratio: '1087/748', label: pair('Site SaaS & design system', 'SaaS website & design system'), description: pair('Un concept de site SaaS et d’espace de travail digital. Une direction sombre, des composants réutilisables et une hiérarchie claire.', 'A SaaS website and digital workspace concept. Dark visual direction, reusable components and a clear hierarchy.'), url: 'https://dribbble.com/shots/27549437-Lumina-AI-Premium-SaaS-Design-System' },
  { id: 'amara', name: 'Chef Amara', categories: ['branding'], image: 'amara.webp', ratio: '1/1', label: pair('Logo & univers culinaire', 'Logo & culinary identity'), description: pair('Une exploration d’identité culinaire autour d’une signature visuelle chaleureuse et d’accents métalliques. Une création de portfolio Sacko Concept.', 'A culinary identity exploration with a warm visual signature and metallic accents. A Sacko Concept portfolio project.'), url: 'https://dribbble.com/shots/27545351-LOGO-OF-CHEF-AMARA' },
];

export const packages = {
  impact: [
    { id:'impact-starter', name:'Impact Starter', price:15, form:'general', tag:pair('Le premier regard', 'A fresh perspective'), desc:pair('Un diagnostic pour savoir exactement quoi améliorer dans votre image.', 'A visual audit to understand exactly what to improve in your presence.'), timeline:pair('Délai indicatif : 2 jours ouvrés', 'Estimated delivery: 2 business days'), items:[pair('Audit de votre profil', 'Profile audit'), pair('3 recommandations ciblées', '3 focused recommendations'), pair('Mini palette de couleurs', 'Mini colour palette'), pair('Bio professionnelle', 'Professional bio'), pair('1 idée de contenu', '1 content idea'), pair('Bonus : ressource Vault', 'Bonus: Vault resource')] },
    { id:'impact-profile', name:'Impact Profile', price:45, form:'general', featured:true, tag:pair('Un profil qui vous ressemble', 'A profile that feels like you'), desc:pair('Les éléments essentiels d’une présence professionnelle, réunis dans un pack.', 'The essentials of a professional presence, brought together in one package.'), timeline:pair('Délai indicatif : 5 jours ouvrés', 'Estimated delivery: 5 business days'), items:[pair('Logo typographique simple', 'Simple typographic logo'), pair('Bannière professionnelle', 'Professional banner'), pair('Bio optimisée', 'Refined professional bio'), pair('3 contenus prêts à publier', '3 ready-to-post visuals'), pair('Mini vitrine digitale', 'Mini digital showcase'), pair('1 révision incluse', '1 revision included')] },
    { id:'impact-business', name:'Impact Business', price:95, form:'general', tag:pair('Une présence complète', 'A complete presence'), desc:pair('Une base visuelle et digitale cohérente pour présenter votre activité.', 'A consistent visual and digital foundation to present your business.'), timeline:pair('Calendrier confirmé après le brief', 'Timeline confirmed after your brief'), items:[pair('Logo : 2 concepts', 'Logo: 2 concepts'), pair('Bio & direction visuelle', 'Bio & visual direction'), pair('5 contenus prêts à publier', '5 ready-to-post visuals'), pair('Mini vitrine avancée', 'Advanced mini showcase'), pair('Stratégie de contenu simple', 'Simple content strategy'), pair('2 révisions incluses', '2 revisions included')] },
  ],
  websites: [
    { id:'website-starter', name:'Starter Express', price:49, form:'website', tag:pair('Votre première vitrine', 'Your first digital home'), desc:pair('Une présence web compacte pour présenter votre offre et être contacté.', 'A compact website to present your offer and help people reach you.'), timeline:pair('Délai indicatif : 3 à 5 jours ouvrés', 'Estimated delivery: 3–5 business days'), items:[pair('Une page vitrine', 'One showcase page'),pair('Présentation de votre activité', 'Business introduction'),pair('Services & appels à l’action', 'Services & calls to action'),pair('Affichage mobile & ordinateur', 'Mobile & desktop layout'),pair('Liens de contact & WhatsApp', 'Contact links & WhatsApp'),pair('Périmètre validé au brief', 'Scope confirmed in your brief')] },
    { id:'website-premium', name:'Premium Design', price:89, form:'website', featured:true, tag:pair('Une vitrine plus affirmée', 'A stronger digital presence'), desc:pair('Une direction graphique soignée pour donner une vraie personnalité à votre site.', 'A considered visual direction to give your website its own personality.'), timeline:pair('Calendrier confirmé après le brief', 'Timeline confirmed after your brief'), items:[pair('Direction visuelle personnalisée', 'Custom visual direction'),pair('Mise en page premium', 'Premium page design'),pair('Présentation claire des offres', 'Clear service presentation'),pair('Sections adaptées au projet', 'Sections tailored to your project'),pair('Navigation & liens de contact', 'Navigation & contact links'),pair('Formats confirmés au devis', 'Formats confirmed in your quote')] },
    { id:'website-pro', name:'Pro Code + Hosting', price:149, form:'website', tag:pair('Un site que vous pouvez faire évoluer', 'A website you can grow'), desc:pair('Une vitrine avec code livré et accompagnement à sa mise en ligne.', 'A website with delivered source files and help getting it online.'), timeline:pair('Délai indicatif : 5 à 7 jours ouvrés', 'Estimated delivery: 5–7 business days'), items:[pair('Site responsive personnalisé', 'Custom responsive website'),pair('Fichiers de code livrés', 'Source code files'),pair('Mise en ligne sur GitHub Pages', 'GitHub Pages deployment'),pair('Métadonnées SEO essentielles', 'Essential SEO metadata'),pair('Accompagnement domaine', 'Domain setup guidance'),pair('Domaine et services payants à part', 'Domain and paid services separate')] },
  ],
  signature: [
    { id:'brand-signature', name:'Brand Signature', price:250, form:'logo', tag:pair('Une identité pensée dans le détail', 'A considered visual identity'), desc:pair('Une identité de marque avec un logo, ses variantes et sa direction graphique.', 'A brand identity with a logo, its variations and a visual direction.'), timeline:pair('Périmètre confirmé après le brief', 'Scope confirmed after your brief'), items:[pair('2 concepts de logo', '2 logo concepts'),pair('Logo principal & monogramme', 'Main logo & monogram'),pair('Variantes de la marque', 'Brand variations'),pair('Palette & direction typographique', 'Colour & typography direction'),pair('Exports PNG, JPG, PDF & SVG', 'PNG, JPG, PDF & SVG exports'),pair('2 séries de révisions', '2 revision rounds')] },
    { id:'ui-signature', name:'Product UI', price:477, form:'website', featured:true, tag:pair('Votre produit, sous son meilleur jour', 'Your product, at its best'), desc:pair('Une direction d’interface premium pour un site SaaS ou un produit digital.', 'Premium interface direction for a SaaS website or digital product.'), timeline:pair('Écrans & calendrier définis au devis', 'Screens & timeline agreed in your quote'), items:[pair('Direction visuelle du produit', 'Product visual direction'),pair('Maquettes de site ou dashboard', 'Website or dashboard mockups'),pair('Hiérarchie & parcours utilisateur', 'Hierarchy & user journey'),pair('Composants d’interface cohérents', 'Consistent interface components'),pair('Adaptations responsive convenues', 'Agreed responsive adaptations'),pair('Design uniquement, code sur devis', 'Design only; development quoted separately')] },
    { id:'intake-system', name:'Client Intake', price:47, form:'intake', tag:pair('Un début de projet plus organisé', 'A more organised project start'), desc:pair('Un brief client à votre image pour collecter les informations utiles.', 'A branded client brief to collect the information you need.'), timeline:pair('Périmètre & connexion validés au brief', 'Scope & connection agreed in your brief'), items:[pair('Formulaire personnalisé', 'Custom form'),pair('Questions adaptées à votre activité', 'Questions tailored to your business'),pair('Direction graphique de votre marque', 'Your brand visual direction'),pair('Suivi des réponses défini ensemble', 'Response workflow agreed together'),pair('Parcours client clair', 'Clear client journey'),pair('Options & outils confirmés au devis', 'Tools & options confirmed in your quote')] },
  ],
};

export const briefs = [
  { key:'general', title:pair('Brief général & packs Impact', 'General brief & Impact packages'), description:pair('Identité, audit, création sur mesure et demandes générales.', 'Identity, audits, custom creative work and general requests.'), number:'01' },
  { key:'website', title:pair('Site web & landing page', 'Website & landing page'), description:pair('Pages, objectifs, contenu, références et style de votre site.', 'Pages, goals, content, references and website style.'), number:'02' },
  { key:'logo', title:pair('Logo & identité de marque', 'Logo & brand identity'), description:pair('Votre activité, votre personnalité et votre direction visuelle.', 'Your business, personality and visual direction.'), number:'03' },
  { key:'banner', title:pair('Bannière & profil', 'Banner & profile'), description:pair('Facebook, LinkedIn, YouTube et présence professionnelle.', 'Facebook, LinkedIn, YouTube and professional presence.'), number:'04' },
  { key:'content', title:pair('Création de contenu', 'Content creation'), description:pair('Votre audience, vos plateformes et vos publications.', 'Your audience, platforms and publication needs.'), number:'05' },
  { key:'intake', title:pair('Système de brief client', 'Client intake system'), description:pair('Formulaire personnalisé et organisation de vos demandes.', 'Custom form and organisation of client requests.'), number:'06' },
];
